# Generated by Django 6.0.4 on 2026-04-19 08:17

from django.db import migrations

import colorfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtype",
            name="color",
            field=colorfield.fields.ColorField(default="#ff0000", image_field=None, max_length=25, samples=None),
        ),
    ]
