# Generated by Django 4.2.16 on 2024-10-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channel",
            name="is_interesting",
        ),
        migrations.AddField(
            model_name="organization",
            name="is_interesting",
            field=models.BooleanField(default=True),
        ),
    ]
