# Generated by Django 4.2.19 on 2025-02-25 08:56

from django.db import migrations, models

import webapp.models.base


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channel",
            name="category",
        ),
        migrations.AlterField(
            model_name="messagepicture",
            name="picture",
            field=models.ImageField(max_length=255, upload_to=webapp.models.base._telegram_picture_upload_to_function),
        ),
        migrations.AlterField(
            model_name="profilepicture",
            name="picture",
            field=models.ImageField(max_length=255, upload_to=webapp.models.base._telegram_picture_upload_to_function),
        ),
    ]
