# Generated by Django 4.2.19 on 2025-02-25 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0002_remove_channel_category_alter_messagepicture_picture_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
