# Generated by Django 4.2.16 on 2024-11-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0003_searchterm_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchterm",
            name="last_check",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
