# Generated by ChatGPT on 2025-02-25

from django.db import migrations, models

import webapp.models.base


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0003_delete_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageVideo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("_created", models.DateTimeField(auto_now_add=True)),
                ("_updated", models.DateTimeField(auto_now=True)),
                ("telegram_id", models.BigIntegerField()),
                (
                    "video",
                    models.FileField(max_length=255, upload_to=webapp.models.base._telegram_picture_upload_to_function),
                ),
                ("date", models.DateTimeField(null=True)),
                ("message", models.ForeignKey(on_delete=models.deletion.CASCADE, to="webapp.message")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
