# Generated by Django 4.2.18 on 2025-01-23 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0004_alter_searchterm_last_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="is_lost",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="channel",
            name="category",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="webapp.category"
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="organization",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="webapp.organization"
            ),
        ),
    ]
