# Generated by Django 6.0.2 on 2026-03-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_messagevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='last_hole_check_max_telegram_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
