# Generated by Django 6.0.2 on 2026-03-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0005_channel_last_hole_check_max_telegram_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchterm",
            name="word",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
