# Generated by Django 6.0.3 on 2026-03-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_searchterm_word_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_user_account',
            field=models.BooleanField(default=False),
        ),
    ]
