# Generated by Django 6.0.3 on 2026-03-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0007_channel_is_user_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="media_type",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
