# Generated by Django 6.0.4 on 2026-04-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0008_message_media_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="pending_forward_telegram_id",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
