# Generated by Django 6.0.4 on 2026-04-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0009_add_pending_forward_telegram_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
