# Generated by Django 6.0.4 on 2026-04-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0012_searchterm_lowercase_remaining"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("_created", models.DateTimeField(auto_now_add=True)),
                ("_updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("channels", models.ManyToManyField(blank=True, related_name="groups", to="webapp.channel")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
