# Generated by Django 6.0.4 on 2026-04-28 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0013_channelgroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageReaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("emoji", models.CharField(max_length=64)),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reactions", to="webapp.message"
                    ),
                ),
            ],
            options={
                "ordering": ["-count"],
                "unique_together": {("message", "emoji")},
            },
        ),
    ]
