# Generated by Django 6.0.4 on 2026-05-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0028_message_replies_unavailable"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="replies_fetched",
            field=models.BooleanField(default=False),
        ),
    ]
