# Generated by Django 6.0.5 on 2026-05-11 14:02

from django.db import migrations, models


def backfill_fwd_from_date(apps, schema_editor):
    """Pre-populate fwd_from_date for forwards whose source message is already in the DB."""
    Message = apps.get_model("webapp", "Message")
    for msg in Message.objects.filter(
        forwarded_from__isnull=False,
        fwd_from_channel_post__isnull=False,
        fwd_from_date__isnull=True,
    ).iterator():
        try:
            original = Message.objects.get(
                channel_id=msg.forwarded_from_id,
                telegram_id=msg.fwd_from_channel_post,
            )
            if original.date:
                msg.fwd_from_date = original.date
                msg.save(update_fields=["fwd_from_date"])
        except Message.DoesNotExist:
            pass


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0030_message_stats_refreshed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="fwd_from_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(backfill_fwd_from_date, migrations.RunPython.noop),
    ]
