# Generated by Django 6.0.5 on 2026-05-15 12:01

import django.db.models.deletion
from django.db import migrations, models

import webapp.models.base


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0035_message_is_lost"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageOtherMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("_created", models.DateTimeField(auto_now_add=True)),
                ("_updated", models.DateTimeField(auto_now=True)),
                ("telegram_id", models.BigIntegerField()),
                (
                    "media_file",
                    models.FileField(max_length=255, upload_to=webapp.models.base._telegram_picture_upload_to_function),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("date", models.DateTimeField(null=True)),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="webapp.message")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
