# Generated by Django 6.0.5 on 2026-05-15 15:14

import django.db.models.deletion
from django.db import migrations, models

import webapp.models.base


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0036_messageothermedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagevideo",
            name="is_animated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="messagevideo",
            name="is_round",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="MessageAudio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("_created", models.DateTimeField(auto_now_add=True)),
                ("_updated", models.DateTimeField(auto_now=True)),
                ("telegram_id", models.BigIntegerField()),
                (
                    "audio",
                    models.FileField(max_length=255, upload_to=webapp.models.base._telegram_picture_upload_to_function),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("is_voice", models.BooleanField(default=False)),
                ("date", models.DateTimeField(null=True)),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="webapp.message")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MessageSticker",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("_created", models.DateTimeField(auto_now_add=True)),
                ("_updated", models.DateTimeField(auto_now=True)),
                ("telegram_id", models.BigIntegerField()),
                (
                    "sticker",
                    models.FileField(max_length=255, upload_to=webapp.models.base._telegram_picture_upload_to_function),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("is_animated", models.BooleanField(default=False)),
                ("date", models.DateTimeField(null=True)),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="webapp.message")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
