# Generated by Django 6.0.5 on 2026-05-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0037_messagevideo_is_animated_messagevideo_is_round_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="grouped_id",
            field=models.BigIntegerField(db_index=True, null=True),
        ),
    ]
