# Generated by Django 6.0.5 on 2026-05-16 04:26

from django.db import migrations, models

import webapp.models.base


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0038_alter_message_grouped_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilepicture",
            name="mime_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profilepicture",
            name="thumbnail",
            field=models.ImageField(
                blank=True, max_length=255, upload_to=webapp.models.base._telegram_picture_upload_to_function
            ),
        ),
    ]
