# Generated by Django 6.0.5 on 2026-05-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0040_backfill_profilepicture_mime_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["channel", "is_lost"], name="webapp_msg_chan_lost_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["channel", "date"], name="webapp_msg_chan_date_idx"),
        ),
    ]
